version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: eatzy_demodb
    restart: always
    environment:
      - POSTGRES_DB=eatzy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fastapiappnetwork

  app:
    image: eatzy
    container_name: eatzy_demoapp
    ports:
      - 8000:8000
    volumes:
      - .:/home
    depends_on:
      - db
    networks:
      - fastapiappnetwork
